### PR TITLE
pull origin, not just fetch

### PR DESCRIPTION
**Pull request by milescalabresi**
this way, it will retrieve updates to existing branches

### CODE REVIEW

**Comment by milescalabresi** [comment]
Fixes #2509

**Comment by benjaminjkraft** [comment]
It might be better to checkout `origin/$NEWBRANCH` instead.  I'm not sure if this will do the right thing in every case if we have a local branch in some unknown state.

**Comment by milescalabresi** [comment]
oh, right. Better now?

**Comment by benjaminjkraft** [comment]
Sorry, I should have been clearer: if you're using `origin/$NEWBRANCH` instead, you can just do the `fetch`, not the `pull`, which is simpler and has less that can go wrong.

**Pull request merged**
