### PR TITLE
Improvements to StudentExtraCosts and DonationModule

### LINKED ISSUE #1327: Allow arbitrary amount for line item types with options
When using the extra costs module to ask for donations, currently the user can only select donation amounts that are predetermined and created as line item options.

It would be useful if the `LineItemType` had a setting to allow arbitrary amounts, in addition to any possible options that are created.

The accounting controller already supports this. The extra costs module would need some changes to support this.

Requested by Ben Horowitz.

### PR DESCRIPTION
**Pull request by pricem**
Joel did some work on this during the fall to address ticket #1327.  We would like to get this merged first before adding the other code changes he has for #1320 and #1319.  I followed up with some interface improvements to StudentExtraCosts, which were necessary for #1327 to be understandable to users, but also overdue in general.

The main change here is to add an "is_custom" boolean field to LineItemOptions.  If you check this in the admin interface, the students will be able to type in any dollar amount they please when they select that line item option.  

The main application of this is donations.  The donation module has also been cleaned up to use an actual Django form, although it is still possible to collect donations through the extracosts module.

Fixes #1327.

### CODE REVIEW

**Comment by luac** [comment]
It looks like there are merge conflicts with accounting and jQuery UI.

I think it was also mentioned that jQuery UI 1.11 breaks the comm panel?

**Comment by benjaminjkraft** [comment]
Yeah, some things got deprecated in 1.9 and removed in 1.10 that the comm panel was using.  The updates probably aren't that hard to do, but we should make sure it didn't break anything else similarly, since there were a bunch of deprecations in 3 version bumps.

**Comment by benjaminjkraft** [comment]
jQuery UI will no longer be an issue once we merge #1839.  This is going to need a merge with main, and the migrations will need to be updated for 1.8.  Does anyone want to take a look at doing that?

**Comment by mgersh** [comment]
This isn't on any sites right now, right? If it is, we have diverged migrations and we'd need to do something about that.

**Comment by benjaminjkraft** [comment]
I don't think so.

**Comment by milescalabresi** [comment]
Can I bump this? A few chapters have requested some line item enhancements mentioned here. As of now, #1839 and #1779 (which I think addresses the 1.8 migration issues) are merged. I believe we're aiming for consistency a more recent version of Django, but I don't understand the current merge conflicts GitHub is reporting.

**Comment by milescalabresi** [comment]
Bump again. This request is mostly done and is a pretty central module for a lot of schools, so it'd be great if we can get it in this release! @benjaminjkraft I remember you saying that something needed to be done beyond just the usual testing/reviewing -- was it just the migration for django 1.8 or is there more? Of likely interest to @bhorowitz @kkbrum @willgearty @ellismiskell

**Comment by benjaminjkraft** [comment]
There are a lot of merge conflicts on the branch; those will need to be fixed if nothing else.  Since it's been a while, I think this will need to be fairly thoroughly retested and rereviewed to make sure things still look ok despite other changes to the site in the meantime.  (For example, does the new user cost view page work correctly with this functionality?)  I think the jquery stuff is all resolved so that can just be removed from this branch.

Honestly, though, this is a nontrivial set of changes to important parts of the site, so I'd much prefer to have it sitting on some chapter sites for a bit before we put it in a stable release.  I'm happy to merge it to specific chapters in any case, and I think we'll need to do another stable release before too long since Django 1.8 is hitting end of support, so hopefully we can get it out before the fall.  If it's ready to merge before we cut the release, we can discuss further if you really want to include it, but I would definitely not like to block the release on it since everything else is very close to ready to go and this has no clear owner and nontrivial work yet to do.

**Comment by milescalabresi** [comment]
Okay, I didn't realize that it had so much more to do. Maybe Katherine and Ellis would be interested in beta-testing it on the Yale site? Then depending on how that goes, perhaps we can put it in the next release.

**Comment by kkbrum** [comment]
We're pretty much done with student reg for Splash right now (and wouldn't want to break anything currently), but could test with fall Sprout (October) if that would help people. Haven't really looked into what this all is though.

**Comment by kkbrum** [comment]
The things I tested/fixed in this PR are student extra costs (custom options for line items), donation module (custom amounts), and credit card module (incorporating the previous two things as well as the offer_donation part of the credit card page).

In addition to reviewing the above, something I'd love help on is making sure that there aren't other implications of the 2015 code for this PR that I haven't considered/tested/fixed.

**Comment by milescalabresi** [comment]
Can the custom options please be displayed for the students? I entered different amounts for different pizza options, but I can only see the main one entered:
image

**Comment by kkbrum** [comment]
So I'm a little confused by what you want. If you want different options with different costs, you just fill out the "amount dec" for each option and leave the "is custom" UNchecked. If you want the student to be able to fill out any amount for an option, then you check the "is custom" box and then the student enters the amount, so whatever you set for the amount is moot. Does that make sense/ what were you expecting/ how would you want it to work?

**Comment by milescalabresi** [comment]
Ah, I didn't realize what "is custom" meant. Thanks

**Comment by kkbrum** [comment]
No worries, I just added help text to the field to clarify!

**Comment by milescalabresi** [comment]
I just added a fix that allows the student schedules to render. I still have to check the donation module update, but the custom amounts feature looks good!

**Comment by kkbrum** [comment]
Ooh I forgot to check student schedules! Good catch!

**Pull request merged**
