### PR TITLE
Feature report: program_size_max=0 is useful

### PR DESCRIPTION
**Pull request by mgersh**
Let's document it so the student reg mainpage can load faster. This eliminates a really slow query on large MIT programs, which in the past have just had program_size_max set to some huge number.

### CODE REVIEW

**Comment by luac** [comment]
Why is this a nullable field? What's the difference between null and 0?

**Comment by mgersh** [comment]
There's no difference, null is treated the same as 0. Note that it doesn't have blank=True, the program creation form and the admin panel won't actually let you set it to null.

**Comment by luac** [comment]
Okay. Seems like it would make more sense to have blank=True and use null as the only "no cap" value, but it's not a big difference.

**Comment by mgersh** [comment]
I'd rather not go messing with this to try to get rid of the 0 option right now.

**Comment by benjaminjkraft** [comment]
This seems fine to me; if we want to do anything else we can make an issue at that point.

**Pull request merged**
