### PR TITLE
Monospace Font for QSD

### PR DESCRIPTION
**Pull request by wnavarre**
Set standalone QSD edit page to use a monospace font for editing the HTML/markdown.

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
Whoa, magic!  I'm going to merge this manually so I can squash it.

**Comment by benjaminjkraft** [comment]
Merged as 9691330e.

**Comment by benjaminjkraft** [comment]
Also, since it may not be clear what the actual change was from the commit message:
screenshot

**Comment by benjaminjkraft** [comment]
Oh, @mgersh just pointed out to me that probably you meant to make both changes that were in this branch.  (One had been reverted.)  I've merged the other one as 2174cdbe.  It now looks like this:
screenshot of QSD editor with formatting bar and markdown

**Comment by wnavarre** [comment]
Wait so the pull request was affected when I did that revert? O.o I didn't expect that. (So is a pull request essentially a pointer to my branch, and whatever I do to my branch mutates the pull request accordingly? I was sort of imagining that a pull request was a 'diff' or a 'patch'). 

Anyway, I reverted that because Favyen said it would be better to assign it to a class that would give us monospace. This solution isn't that bad though because for example the class monospace (in main.less) is kind of bad because it specifies Courier New but I prefer if it's generic monospace so it uses whatever monospace the user prefers.

**Comment by mgersh** [comment]
Yeah, pull requests are branches, and if you push to the branch you'll change the pull request. See for example the giant multi-person mess on #955.

Your second change alone (the class="wide markdown" one) doesn't give us monospace, it gives us what's shown in the first screenshot, which is a toolbar thing that wasn't there before. Both changes together give us both that and monospace.

**Comment by benjaminjkraft** [comment]
> Anyway, I reverted that because @fbastani said it would be better to assign it to a class that would give us monospace.

Yeah, that would be ideal; if you want to make another pull request to fix it, that would be cool.  But we've already got plenty of inline styles, and they're not entirely bad, so I'm fine with it in this case.  You can definitely make another style that uses the default monospace font if you prefer, but if you're going to change it globally you should see what else already uses it, and if we are likely to care.

**Pull request closed without merging**
