### PR TITLE
Progress bars for starred classes

### LINKED ISSUE #382: Progress bar per-timeblock in lottery interface
Have a progress bar in each timeslot in the lottery interface that shows how many interested classes a student has selected up to a maximum of n.  This will hopefully discourage students from listing only one or two classes and then being disappointed when they don't get many classes.

### LINKED ISSUE #1437: Show a "you're done!" in the two-phase lottery
There's no indication that you're done, and your submissions have been saved.  A notification of some sort might be useful, although when to put it could be a difficult question.

### PR DESCRIPTION
**Pull request by willgearty**
Adds a progress bar for each timeslot in two phase registration that reports the number of starred classes for that time slot out of the desired number of starred classes (use tag `num_stars`, default = 10).

Fixes #382.
Also maybe fixes #1437, although I'm in favor of also implementing #1166.

image

### CODE REVIEW

**Comment by willgearty** [comment]
Also, does anyone know if there is a way to change how many breaks the progress bar has?
Ideally, you would want it to have the same number of segments as the number of classes you want a student to star, otherwise it seems the default is 8 segments/7 breaks.

**Comment by willgearty** [comment]
The bootstrap progress bar seems like a reasonable alternative for now. I'll implement that as soon as I get a chance.

And you're totally right, the priority classes seem out of place now. A second progress bar would be nice, although would we still include the "Priority/1", etc. text beneath it?

You're last idea (in parens) might be nice. Basically have a list of n items (where n is the number of priority classes for each slot) and then fill in the class if one is selected (with a little checkmark next to it) or put an alert symbol if a class has yet to be selected?

**Comment by benjaminjkraft** [comment]
> Basically have a list of n items [...]

Yeah, that's the idea.  That way it's clear what they need to do -- the missing priority will be clearly called out.

**Comment by willgearty** [comment]
Thanks for the great suggestions; here's what it looks like now:

image

My last thought: is 10 too many? Especially for small programs? Even though there's a tag to change it, I feel like maybe it's a little high for the default?

**Comment by willgearty** [comment]
@benjaminjkraft Thoughts on this?

**Pull request merged**
