### PR TITLE
Onsite checkout module

### PR DESCRIPTION
**Pull request by willgearty**
This module adds a new record to keep track of students that have checked _out_ of a program (as opposed to check _in_). The module allows an onsite user to select a student with a search bar, then choose which classes, if any, the student will be unenrolled from when they are checked out. The three options given do not affect the `checked_out` record that is created, rather they are short-hands to select the correct classes in the schedule below for unenrollment. There is also an option to check out all students that have checked in (with multiple confirmation checks).

The module itself is done, but I marked this as "Work in progress" because the record doesn't actually affect anything else on the site at this point.

image

Fixes https://github.com/learning-unlimited/ESP-Website/issues/2874, and thanks to the SplashCon admins that helped design this!

### CODE REVIEW

**Comment by kkbrum** [comment]
When you select a specific student who is not yet checked in, I think a little popup should come up saying that the student has not been checked in to the program and asking you whether you want to also check them in before you check them out

**Comment by kkbrum** [comment]
If I type in a name but don't select it from the dropdown (either its not there or im just lazy), and hit "checkout", I get this: 

image

**Comment by willgearty** [comment]
I believe the newest commit should address both of these concerns. Let me know if it works!

**Comment by kkbrum** [comment]
Yep, the bug is fixed and I see the note you added. I think for the note (for students who arent checked in), it might look more complete if you add a "Caution: " to the front and an "!" at the end.

**Comment by willgearty** [comment]
You got it, @kkbrum!

**Comment by willgearty** [comment]
@kkbrum ?

**Pull request merged**
