### PR TITLE
Add script to email asking about class cap increases

### PR DESCRIPTION
**Pull request by benjaminjkraft**
Used by MIT sometimes.  Previously done with a mail merge outside the website, but this seemed easier, and is hopefully easier to reuse.

### CODE REVIEW

**Comment by gkanwar** [comment]
Suggestion: we could make this a check box option in the class registration form so we don't have to email

**Comment by benjaminjkraft** [comment]
If we don't want to do that, we could also make a page with "click here to
approve" links; even if they don't directly modify the size they could at
least just go somewhere that another script can import.

**Comment by benjaminjkraft** [comment]
Merged main to fix tests.

**Comment by mgersh** [comment]
Looks fine, and it worked for this Spark. I'll go ahead and merge this. We can do something fancier later if we decide it would be useful.

**Pull request merged**
