### PR TITLE
Django 1.11

### PR DESCRIPTION
**Pull request by willgearty**
This upgrades us from Django 1.8 to Django 1.11. I updated incrementally (1.8->1.9->1.10->1.11) and fixed errors and failing tests as I went. Honestly, this ended up being less work than I was expecting, but there were still a few major changes that I had to address, including the following:

- Updating the LU versions of the [argcache](https://github.com/learning-unlimited/django-argcache) and [admin-tools](https://github.com/learning-unlimited/django-admin-tools) packages
- Fix widgets for template-based rendering
- Fix template rendering arguments (no more `Context` or `RequestContext`, always a `dict` for context)
- Remove uses of the `url` template tag with a string path
- Update other dependencies (django extensions and django formtools, also remove grappelli)
- Replace JSONField

The rest of the release notes are here:
https://docs.djangoproject.com/en/3.1/releases/1.9/
https://docs.djangoproject.com/en/3.1/releases/1.10/
https://docs.djangoproject.com/en/3.1/releases/1.11/

Current testing status is here: https://docs.google.com/document/d/1t8EBlxtRyBx5Gw0gviE6UP_b_4XwyTiTA3Bl1_1mjZU/edit?usp=sharing. I'm planning on testing everything we normally test on my dev server, then I'll push the code to dev3 for the reviewer (probably @kkbrum) to also test everything again.

Fixes https://github.com/learning-unlimited/ESP-Website/issues/2554.

### CODE REVIEW

**Comment by hwatheod** [comment]
Thank you for taking care of this bit of tech debt. Migrations are always a little bit scary and I'm glad this one wasn't too bad.  I've signed up to do some testing, let me know when you've pushed to dev3.

**Comment by willgearty** [comment]
OK, I've pushed this branch to dev3 for testing. I haven't finished testing everything on my dev server, but I believe it's stable enough to push to the live site. Feel free to start testing various things whenever you get a chance @kkbrum and @hwatheod. Thanks!

**Comment by hwatheod** [comment]
> OK, I've pushed this branch to dev3 for testing. I haven't finished testing everything on my dev server, but I believe it's stable enough to push to the live site. Feel free to start testing various things whenever you get a chance @kkbrum and @hwatheod. Thanks!

Should we write any issues we find on the doc, or open issues for them in github?

**Comment by willgearty** [comment]
Hmm... I would say if it's potentially related to/introduced by this PR, feel free to note it in the doc or here in the PR. If it's probably just a bug that exists outside of this PR, probably fine to just file an issue.

**Comment by hwatheod** [comment]
> Hmm... I would say if it's potentially related to/introduced by this PR, feel free to note it in the doc or here in the PR. If it's probably just a bug that exists outside of this PR, probably fine to just file an issue.

Okay.  It can be hard to tell, so in the interest of not creating too many issues, I'll note any findings on this PR unless it's clearly unrelated (like the Sendgrid issue).

**Comment by hwatheod** [comment]
In a few places there are blue buttons that are hard to read.

"Create new program" button at:
https://dev3.learningu.org/manage/programs/ 
Create new program

"Return to the resource management page" at: 
https://dev3.learningu.org/manage/Splash/2020_Fall/resources/restype_import
Return to the resource management page

**Comment by willgearty** [comment]
Oh geez, I guess I've just become desensitized to that bug since it's been around so long (and I'm surprised it hasn't been documented as an issue yet). I've moved it to it's own issue.

**Review by kkbrum — APPROVED** [review]
The only bugs I found were not related to this, so I think it's good to go! Remarkable!

**Pull request merged**
