### PR TITLE
Link the logo to about/welcome.html instead of front page

### PR DESCRIPTION
**Pull request by betaveros**
The front page makes visual impact, but about/welcome.html is more
useful in practice (e.g. far more links).

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
I'm not sure I like this -- people have a strong expectation that the logo will go to the homepage, whether or not that's the most useful page for them to be on.

**Comment by benjaminjkraft** [comment]
(Do others have thoughts on this?  If I'm outvoted, so be it -- this is just one person's opinion.)

**Comment by mgersh** [comment]
I also pointed out in person that it won't work right anyway for sites that use fruitsalad without bubblesfront.

**Comment by wishdasher** [comment]
Miriam brings up a good point. I personally expect it to go to the welcome
page, and I am still surprised sometimes when it doesn't.

On Sun, Dec 11, 2016 at 6:17 PM, Miriam Gershenson <notifications@github.com

**Comment by betaveros** [comment]
I'm not sure what the typical user expects, but the current implementation (theoretically) tests `theme.front_page_style` which controls whether the theme uses bubblesfront

**Comment by mgersh** [comment]
Ah, okay, I wasn't actually paying attention to the diff here, oops. In that case I agree that users would generally expect to end up at the homepage, but I'm not sure bubblesfront counts as the homepage. I think of it more as the page you see before you get the real homepage (I'd call it a "splash page" but that's kinda confusing in this context). But then it sends you to a different "real homepage" depending on which of learn/teach/logo you click, so...I don't know.

**Comment by bhorowitz** [comment]
Since most programs don't upkeep the about/welcome.html currently, at this point this shouldn't be a system wide change. Closing for now.

**Pull request closed without merging**
