### PR TITLE
Give finaid only for line item types marked as such

### PR DESCRIPTION
**Pull request by betaveros**
This doesn't actually work because for_finaid doesn't mean what I
thought it does, but it shows the simple logic changes we need to make.

### CODE REVIEW

**Comment by betaveros** [comment]
Forgot to say this will fix #2070

**Comment by willgearty** [comment]
Any plans to make this actually work?

**Comment by willgearty** [comment]
Any plans to make this actually work @betaveros ?

**Comment by willgearty** [comment]
Closed in favor of #3465.

**Pull request closed without merging**
