### PR TITLE
Fix hide past timeblocks option in grid based class changes

### PR DESCRIPTION
**Pull request by willgearty**
We now filter out both the timeblocks and sections based on whether they have started already (this includes classes that are still going on and classes in the student's schedule if a student is selected), then only render the remaining timeblocks and sections.

Fixes https://github.com/learning-unlimited/ESP-Website/issues/3179.

### CODE REVIEW

**Review by kkbrum — APPROVED** [review]
Glorious!

**Comment by BalaSubramaniam12007** [comment]
Hey @willgearty   @kkbrum 

I was exploring the "Hide past timeblocks" behaviour in the classchange_grid and noticed something that looks like an incomplete fix from this PR.

**What I observed**

`check_timeslots()`  returns `false` as soon as it finds *any* timeslot  that started more than 20 minutes ago:

``` js
if (differenceInMinutes > minMinutesToHideTimeSlot)
    return false;  // hides on ANY past timeslot
```
Real scenario:

1. It's 10:25 AM
2. A class runs 10:00–11:00 AND 11:00–12:00 (two blocks)
3. Block 1 (10:00 AM) is now 25 minutes old → past threshold
4. Block 2 (11:00 AM) hasn't started yet → still future
5. workbench.html sees block 1 is past → returns false > entire class disappears from the grid
6. Admin cannot see or modify a class that is actively running
7. Single-block classes are fine- they only have one timeslot, so "any past" = "all past". 

The bug only surfaces for multi-block classes.

I have a fix ready if this is confirmed as a bug. Happy to open a PR.

**Comment by willgearty** [comment]
I don't know what workbench.html is (I don't believe we have a file with that name), but this is desired behavior. If a class starts in a past timeblock (but continues into present/future timeblock), we don't want to show that class since it has already started. Enrolling a student in a class that has already started means they wouldn't get the full experience and could end up interrupting the class. Therefore, if a user is filtering out past blocks, we don't want to show these multiblock classes.

**Comment by BalaSubramaniam12007** [comment]
Thanks for the quick clarification that makes complete sense. A student enrolling mid-class would miss content and potentially disrupt the session, so hiding it entirely is the right call.

I also want to apologize for the sloppy write-up. 

Thanks again for taking the time to explain the intent behind the design.

**Pull request merged**
