### PR TITLE
Excluded walk-ins from teachers who like running

### PR DESCRIPTION
**Pull request by jerrywu64**
Fairly self-explanatory. I don't think there's an issue open for this right now though.

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
Will this work if there's no open class category?

**Comment by jerrywu64** [comment]
open_class_category might end up as None, I think? Regardless, open class category is used in a whole bunch of scheduling checks-- such as the previous implementation of all_class_sections, so I expect this change won't break anything that wasn't already broken.

**Comment by jmoldow** [comment]
Why would we do this? Why should it matter whether the class is a walkin or not?

**Comment by jerrywu64** [comment]
Walk-ins start on the half hour, so you aren't actually going to be in a hurry if you need to travel to a walk-in from somewhere else on campus.

**Comment by jmoldow** [comment]
There is no special property of walk-ins that means they have to be scheduled on the half hour. This is a fad that MIT happens to be doing right now. It wasn't always that way, might not continue to be that way indefinitely, and is not that way at other chapters that use the walk-in seminar feature. This will break this scheduling check for, e.g. Stanford.

Can't you guys just ignore results that include walk-ins, rather than changing the code?

**Comment by benjaminjkraft** [comment]
It's really nice to remove false positives from scheduling checks, it makes it a lot easier to iterate the checks.  Maybe we should have a half hour walkins setting on the CRMI to control this, because we're eventually going to need that anyway -- I think at MIT the half-hour walkins thing is here to stay.

(OOC, do other chapters even use scheduling checks?  Some are already fairly specific to the way MIT does things, even if other chapters could theoretically use them.)

**Comment by mgersh** [comment]
I'm personally not a fan of putting workaround hacks like this in the codebase, even if we're the only ones using it, especially given that walk-ins are not a huge fraction of the "teachers who like running" false positives. Actually implementing #828 is the long-term solution, and I'm guessing that someone will actually do that within the next couple of years, but not soon enough that we'll remember we put this here and remove it.

**Comment by benjaminjkraft** [comment]
Seems like once #1687 is done this will be less of an issue, so I'm going to close this until such time as we have a real half-hour walk-in solution across the site.  If people still think otherwise, do say so.

**Pull request closed without merging**
