### PR TITLE
Mobile app

### PR DESCRIPTION
**Pull request by pricem**
This branch contains a mobile app for streamlining onsite tasks during a program (an idea that's been requested several times over the years, and has ticket #142).  It was written by Alan Yeo during Google Summer of Code, with mentorship from Andrew Geng.  This is a significant contribution of new code and should be reviewed carefully.

Once you've pulled the code, you can access the mobile app at /media/mobile/build/production/index.html.  (The app is a static HTML page that does everything using Javascript and Ajax.) If you run a dev server with IP 0.0.0.0 (or an actual IP), you can load it up using a mobile device that's on the same network; I've been using a small Chrome window on my PC.

Features include:
- Users: view student registered for a program, view their contact/student info, check in, change grade, modify schedule
- Onsite new user registration (leads to above user control interface)
- Sortable/filterable class catalog with detailed information screen for each class

Main issues to review:
- Does each type of user see an interface that makes sense for their needs at the program?  Does any part of the student workflow need to be adjusted (e.g. require that they've paid and/or turned in forms before using the app)?  Do chapters need the ability to configure permissions?
- Do any of the changes to JSON views conflict with what the non-mobile pages use and/or expect?
- Cross-device/browser compatibility
- Testing for bugs

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
This pull request is now over two years old.  Is there a plan for merging it, or does someone want to work on making this happen?  Do we want to just give up and toss it?

**Comment by bhorowitz** [comment]
I certainly think it would be cool to have a mobile app... Has anyone tested it recently?

**Comment by benjaminjkraft** [comment]
It's quite old, so it would probably be some work to get it actually mergeable with the current codebase.  I think it was supposed to be a mobile website mostly for admins, but I'm not sure exactly -- perhaps someone else can comment?

**Comment by benjaminjkraft** [comment]
This is going to require a lot of work to merge, and nobody's touched it in two years.  I'm going to close the pull request, since having it sitting open just adds clutter to the list; if anyone wants to take it on that would be much appreciated, and you can reopen it at that point.

**Pull request closed without merging**
