### PR TITLE
Fix path-construction in linter

### PR DESCRIPTION
**Pull request by benjaminjkraft**
It broke when moved.  (Edit: to be more specific, it started trying to lint `env`, which it really shouldn't.)

### CODE REVIEW

**Comment by btidor** [comment]
Don't we also want to lint `fabfile.py` and stuff in `deploy`? The old way gets the whole repository.

**Comment by benjaminjkraft** [comment]
If we want that we should specify it explicitly/separately.  If you're running this locally, as is it will try to lint `env`, which is not a plan.  (It does so on Travis too, but I guess `flake8` passes `flake8`, and that's the only thing we install.)

**Comment by benjaminjkraft** [comment]
(Updated to do that.)

**Comment by benjaminjkraft** [comment]
(Talked to @btidor off-thread, going to use excludes instead of linting only certain directories.)

**Comment by btidor** [comment]
+1

**Comment by benjaminjkraft** [comment]
Merging per @btidor's approval now that tests have passed.

**Pull request merged**
