### PR TITLE
Use sudo -H with npm so that it sets $HOME properly

### PR DESCRIPTION
**Pull request by luac**
Since npm tries to read and write $HOME/.npm, there can be issues
running sudo npm when root does not have permissions on $HOME/.npm
(such as if $HOME is in AFS). Fix this by using sudo -H, which sets
$HOME to root's home directory instead.

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
Won't this cause the user to be unable to see the packages they've installed without root, since the user probably can't see `/root/.npm`?  Since `npm` default install locations are really inconsistent by `npm` version and user config, we may want to do `npm install -g ... || sudo npm install -g ...` or something.  (Or we could actually check what `npm prefix` is, and install as root iff the current user can't read it, but that's harder.)

**Comment by luac** [comment]
Hmm, okay. I was going off of the assumption that `npm prefix` was `/usr` or something, which was the case when I encountered the issue that prompted this. I also assume the intent is to install lessc in a place that is visible from everyone's path, so that you don't have to run update_deps as the same user as the web server.

**Comment by luac** [comment]
Looks like `npm install -g --prefix /usr` works?

**Comment by benjaminjkraft** [comment]
I'd prefer if we did *less* installation of global packages and use of `sudo` than before, but I guess that ship has sailed, so yeah, that should be fine.

**Comment by luac** [comment]
I was about to make this change, but then I hesitated because it might break in a confusing way in case this is run on a platform where /usr isn't a thing. I don't know if we care about those.

**Comment by benjaminjkraft** [comment]
I would think any platform with `sudo` would definitely have `/usr`, so I'd say we don't care.

**Pull request merged**
