### PR TITLE
Sentry linting

### PR DESCRIPTION
**Pull request by luac**
I went through the Sentry errors from the MIT site and fixed a bunch of them.

The bad(?) news is that a lot of them were just silly uninteresting edge cases that should've been user errors anyway and/or should've been caught by a linter. The good(?) news is that a lot of them involved awful code that should've been cleaned up anyway and/or will have to be if we eventually want to instate a linter.

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
A couple of minor things, otherwise looks good once tests pass.

**Comment by luac** [comment]
Argh, that was an entirely predictable merge conflict. But anyway, resolved now.

**Comment by benjaminjkraft** [comment]
Yeah, sorry, I had vaguely figured this would get merged first and I would get to resolve it.

**Comment by btidor** [comment]
+++

**Pull request merged**
