### PR TITLE
Send emails to teachers re: cancelled classes

### LINKED ISSUE #2360: Confirm class cancellation email to teachers
Clark Splash has requested a checkbox so that when an admin (or teacher) cancels a class, the website should email all teachers (including co-teachers) of the class. The logic is that if a teacher cancels their own class, the email can serve as a confirmation receipt, and if an admin cancels the class (if teacher emails in with an emergency or if too few students register) it can notify the teacher that the class has been cancelled. Ideally this checkbox would allow an optional message explaining why the class has been cancelled.

### PR DESCRIPTION
**Pull request by willgearty**
When a class/section is cancelled, the website now sends an email to each of the teachers of the class.
Fixes #2360.

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
Hmm, I think I am in favor of having this be optional.  (I don't care what the default is.)  But if we're not going to make it optional, we definitely need to have text that says clearly that teachers will be emailed, especially since it's a behavior change!  We don't want an admin to be surprised that a teacher got an email (whereas it is generally fine to send admin-internal emails without warning).

**Comment by willgearty** [comment]
How about making it optional, but make the option selected by default?

**Comment by willgearty** [comment]
image

**Comment by benjaminjkraft** [comment]
Fine with me!  In general I always hate to add more checkboxes and options, but this one seems both useful and simple enough to add.

**Pull request merged**
