### PR TITLE
Support recurring classes for attendance

### PR DESCRIPTION
**Pull request by willgearty**
This extends the work I did in #2868 to support classes that occur on multiple days but rely on the same timeslot (e.g. Sprout classes). The first step was to make it so that attendance now expires at midnight on the day it is set. This then makes it so we can set or check attendance for specific days. I added a field that allows admins to pick this date for the onsite attendance module (the default is the day of the timeslot). For teachers, they won't notice any difference, except that the students they marked as attending for previous instances of the class will no longer be marked as attending. To make sure all of this is clear, I've made the code a lot clearer with more verbose comments, and I've made the headings for the various tables on the page much clearer and more precise. If a day other than the default is selected, this will be noted in lots of places on the page as a reminder.

image

### CODE REVIEW

**Comment by kkbrum** [comment]
If I click the little blue x in the preferred date box, and wait a couple seconds, this error pops up:

image

**Comment by kkbrum** [comment]
Could you check whether you added code to expire students at end of day who are marked Onsite/AttendedClass when a teacher marks them attended and they weren't previously enrolled? I don't think you did but I could also be confused. Also, if those get expired, would the student still remain actively enrolled in the class (for future week schedule's/ posterity sake)? If not, maybe we need to add double registrations for them so that an attended registration gets expired but the onsite registration remains active?

**Comment by willgearty** [comment]
Hmm...I'm not seeing this little "x" in my browser, but that should be a pretty easy fix (just check that there's a date specified for the when variable).

For your second comment, that list sounds correct to me. My thinking was that a student was enrolled via attendance, not registration, so we'd want to always know that, regardless of what day it is (even for a future instance of the class, the student was still originally enrolled via attendance, not registration), but if we only want to know that for the original day (again, all of this was designed for non-Sprout classes), I can change that (by either expiring the onsite/attendedclass relationship at the end of the day or filtering onsite_srs to only the specified day). I can see it both ways, so we just need to make a decision one way or the other.

**Comment by kkbrum** [comment]
I think it makes sense to expire the onsite/attendedclass registration, since beyond the day of that registration, I would consider a student "enrolled" in a class.

**Comment by willgearty** [comment]
I think that should address both concerns, @kkbrum!

**Pull request merged**
