### PR TITLE
Student attendance (teacher and admin interfaces)

### PR DESCRIPTION
**Pull request by willgearty**
This implements a set of tools for teachers and admins to manage student class attendance.

This adds a new page (`section_attendance`) that allows teachers to take attendance for a particular section (including unenrolled students) (see details in picture below). The page is linked to from the main teacher registration page (for sections that are approved and scheduled). The page has a dropdown menu for the teacher to select a section for attendance.

(I also used the new template tag from https://github.com/learning-unlimited/ESP-Website/pull/2860)

I also added an onsite module that summarizes attendance statistics/details (see details in picture below). The page has a similar dropdown to select a particular timeslot for attendance. The page is linked to from the main onsite page (provided the module is enabled).

Fixes https://github.com/learning-unlimited/ESP-Website/issues/2864.

Teacher interface:
image

Admin interface:
image

### CODE REVIEW

**Comment by kkbrum** [comment]
Comments I have based on the images and text above (havent code reviewed or tested yet though):

- From my understanding, Yale's plan was to have teachers scan all the barcodes of students, not necessarily doing a typical roll call. Thus I think the box in the teacher interface of "enter unenrolled students here" could really be "enter any ids here" just like the advanced barcode check in page works for program attendance, and then you can keep the checkboxes for the conflict students to be unenrolled & enrolled, but maybe add a line above it saying "For any students not enrolled in the section:". Then teachers can either do the checkbox method at the top if they dont have a scanner and care about extra students attending class (ie art classes or super full classes) or they can just scan all the barcodes and not deal with the checkboxes. And then if they do the barcode entry, obviously it would be nice if when they submitted that, the checkboxes above auto filled correspondingly.

For admin interface:
- For "students checked in", it's a little unclear what that means (checked in for program vs checked into a class), so i would specify "Students checked in and attending class"

- Under the latter two boxes (problematic students), can there be a button like "create an AUL filtered to these students" which will jump to AUL where you've already inputted the filter and then the admin can just select which fields they want (ie cell phone, parent phone, etc)

- For the second box (not attending class), i think it would be helpful to have a column for class they are supposed to be in and room number they are supposed to be in. Then an admin can a) go check the room and b) notice that a teacher didnt take attendance of a whole room or something

- can there be a 4th box saying "Sections with no attendance inputted" that gives the section & room number & teacher name & teacher phone number so that the admin knows to go deal with that room somehow

- for the 3rd box, i think there needs to be another column for "enrollment changed to current class" so that the admin knows whether the teacher did the checkmark to auto enroll the kid or not so that they know whether the class changes is up to date for that kid or not

Sorry for all the requests... you're the best! <3 This looks awesome :)

**Comment by willgearty** [comment]
New teacher interface:
image

**Comment by willgearty** [comment]
> Comments I have based on the images and text above (havent code reviewed or tested yet though):
> 
> * From my understanding, Yale's plan was to have teachers scan all the barcodes of students, not necessarily doing a typical roll call. Thus I think the box in the teacher interface of "enter unenrolled students here" could really be "enter any ids here" just like the advanced barcode check in page works for program attendance, and then you can keep the checkboxes for the conflict students to be unenrolled & enrolled, but maybe add a line above it saying "For any students not enrolled in the section:". Then teachers can either do the checkbox method at the top if they dont have a scanner and care about extra students attending class (ie art classes or super full classes) or they can just scan all the barcodes and not deal with the checkboxes. And then if they do the barcode entry, obviously it would be nice if when they submitted that, the checkboxes above auto filled correspondingly.

I've added the barcode scanning functionality from the barcode checkin module (and pulled out the javascript and css to new files to limit code duplication). Scanning a barcode adds it to the `textarea`, but does NOT automatically process it (unlike the default in the barcode checkin module). The `textarea` can also now handle enrolled students (it skips the unenroll/enroll steps). I've modified the text to make all of this clearer to teachers.
> 
> For admin interface:
> 
> * For "students checked in", it's a little unclear what that means (checked in for program vs checked into a class), so i would specify "Students checked in and attending class"

I've clarified the headers for the first box. My thinking here is that ideally you want the three numbers here to be the same (all checked in students for the program are enrolled in classes and are attending those classes in the selected timeslot).

> * Under the latter two boxes (problematic students), can there be a button like "create an AUL filtered to these students" which will jump to AUL where you've already inputted the filter and then the admin can just select which fields they want (ie cell phone, parent phone, etc)

`commpanel.js` (used in the AUL, comm panel, and group texting module) now populates the form fields with GET parameters (e.g. `commpanel?userid=6,7,4,14,5,16` would fill in the 6,7,4,14,5,16 into the `userid` fields). I've added links under each box that will fill in the user IDs for each of these three modules.

> * For the second box (not attending class), i think it would be helpful to have a column for class they are supposed to be in and room number they are supposed to be in. Then an admin can a) go check the room and b) notice that a teacher didnt take attendance of a whole room or something

Done!

> * can there be a 4th box saying "Sections with no attendance inputted" that gives the section & room number & teacher name & teacher phone number so that the admin knows to go deal with that room somehow

Done!

> * for the 3rd box, i think there needs to be another column for "enrollment changed to current class" so that the admin knows whether the teacher did the checkmark to auto enroll the kid or not so that they know whether the class changes is up to date for that kid or not

I've added two columns, one for the class they are attending and one for the class they are enrolled in.

> 
> Sorry for all the requests... you're the best! <3 This looks awesome :)

Here are some new screenshots:
image

image

**Comment by kkbrum** [comment]
Okay so it looks like I still have a number of confusions:
- The box "students checked in during this timeslot" means what? I feel like I've ruled out every option: it cant be all students checked in to the program because there are 7, it cant be students checked in to any class because there should be at least 2, dmalfoy and johndoe, and it cant be students checked in to the correct class because dmalfoy is also in the incorrect class box.
- I feel like since dmalfoy is attending a class, even if its the wrong one, he shouldnt be in the AWOL box. And, why aren't dmalfoy and johndoe both in the AWOL box or both not in the AWOL box if they are both attending wrong classes? I feel like there's something fishy going on here with either dmalfoy or johndoe

If the answer to all this is that johndoe is not checked in to the program itself, then i think that leads to the addition of a box of "students attending classes but not checked in to the program". But that doesn't solve my confusions anyway because the top says  there are 7 students checked in to the program and there are only 6 students aside from johndoe based on the boxes below. 

I think we have to make this page mostly self-explanatory so there's still some work to be done with making the boxes clear.

**Comment by willgearty** [comment]
I've added a 15 minute buffer to the filter for the first wide box (and made the title more specific)

**Comment by willgearty** [comment]
That's weird. Is the "Attended" student registration expired? It only counts unexpired "Attended" srs:
https://github.com/learning-unlimited/ESP-Website/blob/c2d6ba0665369f273bdf213d31894605e85dc5e7/esp/esp/program/modules/handlers/onsiteattendance.py#L101

**Comment by kkbrum** [comment]
Nope, its unexpired

**Comment by willgearty** [comment]
https://shouldiblamecaching.com/???

**Comment by willgearty** [comment]
Did you perhaps mark the student as attending one section, but it's showing another section of the class?

**Comment by kkbrum** [comment]
nopeeeee and nopeeeeeeee

**Pull request merged**
