### PR TITLE
Manage class duration

### LINKED ISSUE #2025: Class durations are not shown in manageclass or classsearch

### PR DESCRIPTION
**Pull request by willgearty**
Adds ability to edit the duration of a class on the manage page.

Fixes #2025.

### CODE REVIEW

**Comment by kkbrum** [comment]
Changing the class duration isn't updating the durations of the sections that already exist

**Comment by willgearty** [comment]
Should now update the section durations @kkbrum

**Comment by willgearty** [comment]
One thought I did have, though, was if we want to do anything special when an admin tries to change the duration of a scheduled class? Like tell them "no"?

**Comment by kkbrum** [comment]
We probably at least want a warning message asking if they want to proceed knowing this could cause:
- teachers to be double booked (if lengthening class)
- students to be double booked (if lengthening) or have an empty block (if shortening)
- rooms to be double booked (if lengthening)
There's little harm in the case of shortening a block, so I think we should potentially let admins proceed if they understand the potential implications?

A warning that goes above and beyond would probably check teacher and room schedules and make sure double booking isnt happening, and checks whether students have signed up yet. That's probably much effort though and a simple warning asking the admin to be certain is probably fine?

**Comment by willgearty** [comment]
Will changing the duration of a scheduled section actually impact many things? If it's already scheduled, the room resource is already set up for the original duration, right? And so it might not even impact schedules, etc? I'm leaning towards just a little note next to the duration field, but I guess I could be persuaded to have a more dramatic and situational warning.

**Comment by kkbrum** [comment]
Oh hmm i just realized what i was originally thinking was that the changed duration would auto update the scheduling, but that wouldnt make sense because it's unclear whether to shorten/lengthen from the end or the beginning of the time. I think I agree now with your original thought of preventing people from changing duration (at least on this page) of a scheduled class... there's not really a good way to deal with it so might as well force the admin to unschedule and then do it so that nothing gets messed up.

**Comment by willgearty** [comment]
That sounds good to me! Check it out now and let me know what you think.

**Pull request merged**
